[build]
  publish = "."

[[redirects]]
  from = "/contact"
  to   = "/contact.html"
  status = 200

[[redirects]]
  from = "/bio"
  to   = "/bio.html"
  status = 200

[[redirects]]
  from = "/press"
  to   = "/press.html"
  status = 200
